### ISSUE TITLE
Unable to Import angular2-web-worker

### ISSUE THREAD

**Issue by ltfschoen** [haochi/angular2-web-worker#1]
I am new to Web Workers, and have attempted to use this library on a project I'm working on, but it is not importing into the Component from node_modules via SystemJS. I am getting the following errors in my browser. I would greatly appreciate any help and happy to create a Pull Request to improve the Readme for other beginners like myself. Here is a branch of my project where I tried to implement it: [Luke's project branch with attempt at using angular2-web-worker](https://github.com/ltfschoen/angularjs2_search/compare/web_workers?expand=1):

```
angular2-polyfills.js:127 GET http://localhost:8000/node_modules/angular2-web-worker/web-worker.service.ts 404 (Not Found)
Error: Error: XHR error (404 Not Found) loading http://localhost:8000/node_modules/angular2-web-worker/web-worker.service.ts
```

**Comment by haochi** [comment]
@ltfschoen You are not supposed to add `angular2-web-worker` to `System.import` directly. Once you have imported it into `book-welcome.component.ts`, it should work. You let TypeScript do the work and transpile.

Maybe try getting rid of the addition in `builds/development/index.html`?

**Comment by dmylian** [comment]
@haochi import `import { WebWorkerService }  from 'angular2-web-worker';` in the component results in `Cannot resolve symbol WebWorkerService` so it obviously can't be injected in the constructor then.

**Comment by David-Mawer** [comment]
Hi @danny-mylian ,

I see that it's been a while, and I guess that you have moved on to another solution - but in case you or anyone else needs it, here is the import statement

`import {WebWorkerService} from 'angular2-web-worker/web-worker.service';`

(the trick is to add **_/web-worker.service_** to the module name)

**Comment by haochi** [comment]
@David-Mawer Thanks :)

**Comment by sunitaw** [comment]
I am getting error message for WebWorkerService  as not able to access, probably located in an unaccessible module.
