### ISSUE TITLE
Umatched Dependency

### ISSUE THREAD

**Issue by iamEse** [haochi/angular2-web-worker#2]
Good day haochi,

I installed your modules however I get the following errors

1. +-- UNMET PEER DEPENDENCY es6-shim@^0.33.3
 2. +-- UNMET PEER DEPENDENCY reflect-metadata@0.1.2
 3. +-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.0
 4.  `-- UNMET PEER DEPENDENCY zone.js@0.5.10

This is a part of my package.json

"zone.js": "^0.6.23"
"rxjs": "5.0.0-beta.12",

Please can I still use the webworker as indicated in the API docs??  If not, how do I use your package??

Thank you

**Comment by haochi** [comment]
@iamEse Resolved :)
