### ISSUE TITLE
Please add public getWorker(fromPromise) to IWebWorkerService

### ISSUE THREAD

**Issue by David-Mawer** [haochi/angular2-web-worker#3]
Hi @haochi ,

Thank-you for the component. I'm needing this in my project; and am gratefull that you have done this for the public.

I have a request, though. Could we have a public function that takes a promise and returns the corresponding worker?

Then I can play around with the worker directly with the `onmessage`, `postMessage ` and `addEventListener` functions of the worker directly myself.

So - to do this - I see that you already have a `promiseToWorkerMap` privately declared in `web-worker.ts`
Also, there is private code that gets the worker from the promise.

So it should be possible to update the IWebWorkerService interface to include a

`getWorker<T>(promise: Promise<T>): Worker`

I be happy to do this - but I'm new to GitHub; So don't know how to do this on your public repository. But would prefer to have this as part of your package because if I have to make a local copy and do it myself; then no-one else gets to benefit.

So - Please let me know if you are still actively supporting this package, and if you consider this a change worth doing?

Sincere thanks & regards,
David Mawer :-)

**Comment by haochi** [comment]
@David-Mawer Done. :)
